'*': npm run lint:editorconfig && npm run lint:fs
'*.{js,jsx,scss,json,md,html}': npm run prettify
client/src/**/*.{js,jsx}: npm run lint:client:js
client/src/**/*.scss: npm run lint:client:css
server/**/*.js: npm run lint:server:js
